#ifndef TENSORFLOW_LITE_MICRO_FOOD_MENU_RECOGNITION_CNN_DATA_H_
#define TENSORFLOW_LITE_MICRO_FOOD_MENU_RECOGNITION_CNN_DATA_H_

extern const unsigned char food_menu_recognition_tflite[];
extern const int food_menu_recognition_tflite_len;

#endif  // TENSORFLOW_LITE_MICRO_FOOD_MENU_RECOGNITION_CNN_DATA_H_

